[package]
name = "lw-photo-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1"
ogl33 = { version = "0.2.0", features = ["debug_error_checks"]}
beryllium = "0.8.0"
imagine = "0.0.5"
image = "0.24.3"
glitz = "0.4.0"
zstring = "0.1.3"

[dev-dependencies]
