[package]
name = "lw-photo-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
eframe = "0.19.0"
egui_extras = { version = "0.19.0", features = ["image"] }
turbojpeg = {version = "0.5.2", features = ["image"]}
spng = "0.1.0"

[dev-dependencies]
